spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_event?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true # Creating database "campus_event" if it doesn't exist
    username: root  # MySQL username
    password: 2795  # MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Automatically creates/updates tables
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080